# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5431:5432

  adminer:
    container_name: postgres
    image: adminer
    restart: always
    ports:
      - 9080:8080
  version: '3'

  smtp4dev:
      image: rnwood/smtp4dev:v3
      restart: always
      ports:
        # Change the number before : to the port the web interface should be accessible on
        - '9081:80'
        # Change the number before : to the port the SMTP server should be accessible on
        - '9025:25'